#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${PROJECT_ID:?Set PROJECT_ID}"
JOB_SERVICE_ACCOUNT="${JOB_SERVICE_ACCOUNT:?Set JOB_SERVICE_ACCOUNT to risk-dashboard-jobs@<PROJECT_ID>.iam.gserviceaccount.com}"

REGION="${REGION:-us-east1}"
AR_LOCATION="${AR_LOCATION:-$REGION}"
AR_REPO="${AR_REPO:-risk-dashboard-jobs}"
IMAGE_NAME="${IMAGE_NAME:-risk-dashboard-jobs}"
IMAGE_TAG="${IMAGE_TAG:-$(date -u +%Y%m%d-%H%M%S)}"

SKIP_BUILD="${SKIP_BUILD:-false}"
DEPLOY_ALERT_JOBS="${DEPLOY_ALERT_JOBS:-true}"
DEPLOY_REFRESH_MVS_JOB="${DEPLOY_REFRESH_MVS_JOB:-true}"

LLM_PROVIDER="${LLM_PROVIDER:-gemini}"
LLM_MODEL="${LLM_MODEL:-gemini-2.5-flash}"
LLM_MAX_CALLS="${LLM_MAX_CALLS:-200}"
LLM_SUMMARY_MAX_CALLS="${LLM_SUMMARY_MAX_CALLS:-20}"

DASHBOARD_BASE_URL="${DASHBOARD_BASE_URL:-https://risk-dashboard-168007850529.us-west1.run.app}"

export PROJECT_ID JOB_SERVICE_ACCOUNT REGION AR_LOCATION AR_REPO IMAGE_NAME IMAGE_TAG
export SKIP_BUILD DEPLOY_ALERT_JOBS DEPLOY_REFRESH_MVS_JOB
export LLM_PROVIDER LLM_MODEL LLM_MAX_CALLS LLM_SUMMARY_MAX_CALLS DASHBOARD_BASE_URL

bash scripts/deploy_cloud_run_jobs.sh
