name: 'Setup Python Environment'
description: 'Set up Python with pip caching and install project dependencies'
author: 'patrick'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.11'
  requirements-file:
    description: 'Path to requirements.txt file'
    required: false
    default: 'requirements.txt'

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: ${{ inputs.requirements-file }}
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f "${{ inputs.requirements-file }}" ]; then
          echo "Installing from ${{ inputs.requirements-file }}..."
          pip install -r "${{ inputs.requirements-file }}"
        else
          echo "Warning: ${{ inputs.requirements-file }} not found, skipping dependency installation"
        fi
    
    - name: Verify installation
      shell: bash
      run: |
        echo "Python version: $(python --version)"
        echo "Pip version: $(pip --version)"
        echo "Installed packages:"
        pip list
